### PR TITLE
This look good?

### PR DESCRIPTION
**Pull request by aditya1999**
Updated "stats" and "our team" sections

### CODE REVIEW

**Comment by Chaitya62** [comment]
Crazy commit messages

**Comment by inishchith** [comment]
@Freelancer-98 Let go of the gifs for now . Just pull his fork and watch

**Comment by nurdtechie98** [comment]
@inishchith I feel the timeline looks somewhat incomplete without the images do check it out.
what do you think @aditya1999 ??

**Comment by aditya1999** [comment]
I did think so too. Also, the one lines descriptions that were removed and replaced with the position of the member, seems unnecessary. However having nothing there makes the site look incomplete. So what should I do?

**Comment by nurdtechie98** [comment]
@inishchith @Freelancer-98 @shivam1708  any alternatives in your mind?

**Comment by inishchith** [comment]
@nurdtechie98 @aditya1999 I've been away . I'll check in some time .

**Comment by inishchith** [comment]
@nurdtechie98 @aditya1999 Yes 🙈 . what do we do ?

**Comment by nurdtechie98** [comment]
Should we add our photos I can't think of something better.

**Comment by inishchith** [comment]
@nurdtechie98 Cool . @aditya1999 See the time-line view it's unusual (not Zig-Zag)

**Comment by aditya1999** [comment]
Done @inishchith

**Comment by inishchith** [comment]
@aditya1999 Nice ✨  . Remaining now : Adding Photos or any other alternative . We'll wait ;)

**Comment by inishchith** [comment]
@nurdtechie98 Any Updates ?

**Comment by nurdtechie98** [comment]
we haven't finalised the design @inishchith as now we'll have to pick one among the few suggested

**Pull request merged**
